### ISSUE TITLE
Can not get sid

### ISSUE THREAD

**Issue by phamxtien** [redscorpse/perplexity.ai-cli#1] opened 2024-04-21 12:21 UTC
Welcome to perplexity.ai CLI!
Enter/Paste your content. Enter + Ctrl-D (or Ctrl-Z in windows) to send it.
To check the references from last response, type `$refs`.

 >  hello
Traceback (most recent call last):
  File "............../perplexity.ai-cli.py", line 190, in <module>
    main()
  File "............../perplexity.ai-cli.py.py", line 176, in main
    answer = list(Perplexity().generate_answer(prompt))
                  ^^^^^^^^^^^^
  File "............../perplexity.ai-cli.py.py", line 29, in __init__
    self.sid = loads(
               ^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by redscorpse** [comment] 2024-04-21 12:58
This was fixed in last commit, make sure you have done `git fetch && git pull`:
```diff
-            "User-Agent": "Ask/2.4.1/224 (iOS; iPhone; Version 17.1) isiOSOnMac/false",
+            "User-Agent": "Ask/2.4.1/224 (iOS; iPhone; Version 17.4) isiOSOnMac/false",
```

**Closed as completed** 2024-04-21 14:40 UTC

**Comment by phamxtien** [comment] 2024-04-21 22:31
Many thanks.
A question: How to save the session for reuse after the end of the program?

**Comment by redscorpse** [comment] 2024-04-22 12:56
The intention of this project is the equivalent of using perplexity.ai from a private browser. If you want to use it like the paid api you should do more complex stuff like reversing it. I also turned [Zai-Kun/reverse-engineered-chatgpt](https://github.com/Zai-Kun/reverse-engineered-chatgpt) into an interface like the one you are using in this repo, however I prefer perplexity over chatgpt for many reasons... You can try Zai-Kun's projet and if you really like it more I can share you my fork (or maybe I could push it on a new branch). But right now the solutions I can give you are a) checking Zai-Kun's project; b) if you want to save the conversation you can run it with `perplexity.ai-cli | tee myOutput.txt`; c) keep the session open with tmux or manage the process with <kbd>ctrl-z</kbd> & `fg`.

**Comment by phamxtien** [comment] 2024-04-24 23:16
It get error again
![Screenshot from 2024-04-25 06-13-08](https://github.com/redscorpse/perplexity.ai-cli/assets/33739597/d2d3c313-08e4-48ee-ba04-50a9cfaabd2c)
May be cause by Cloudflare

**Comment by redscorpse** [comment] 2024-04-25 17:24
@phamxtien right now it works for me, try to clone the repo again.

![IMG_9316](https://github.com/redscorpse/perplexity.ai-cli/assets/73442486/ae3822c6-9250-4110-86f1-398267be84d9)

**Comment by phamxtien** [comment] 2024-04-27 00:29
I just clone this repo
![image](https://github.com/redscorpse/perplexity.ai-cli/assets/33739597/94d61387-bf40-4392-bb7d-a22629a6cfe9)
an still get error
![image](https://github.com/redscorpse/perplexity.ai-cli/assets/33739597/7bba2555-c563-449d-bd35-e8e407aaba73)
System: Ubuntu
Python 3.12

**Comment by redscorpse** [comment] 2024-04-27 03:44
I've run it from another computer once again and it also works. I am using Python 3.11.4, requests 2.31.0 and websocket-client 1.8.0
I can't reproduce your error. Try to debug the code by yourself. The `self.sid` variable what is taking is the `sid` value from an url, you can try adding this line of code before line 29:
```python
print(f"https://www.perplexity.ai/socket.io/?EIO=4&transport=polling&t={self.t}"); exit()
```
If then you copy and paste the url in your browser you should get something like this:
```
0{"sid":"Zt-6cCLJZ-iEBQ22AF8B","upgrades":["websocket"],"pingTimeout":20000,"pingInterval":25000}
```
where `self.sid = "Zt-6cCLJZ-iEBQ22AF8B"` (but this value changes on each session so you can't define it manually), but try to debug it like that to see where it fails. 

I can't help you more because i am not getting this error any more.

**Comment by phamxtien** [comment] 2024-04-27 23:38
Many thanks for your support, i will try.

**Comment by phamxtien** [comment] 2024-04-28 03:26
Follow your guide, now I can make it run smooth.
Many thanks again

**Comment by phamxtien** [comment] 2024-12-20 12:23
@redscorpse 
I got error and just clone newest code and it seems not pass cloudflare again :)
When I print 
```
print(self.session.get(url=URL).text[1:])
```
It returns
```
!DOCTYPE html>
<html lang="en-US">
<head>
<title>Just a moment...</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="robots" content="noindex,nofollow">
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}body{display:flex;flex-..........
........................
</html>
```
